version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:test-php-latest-rhel-8
    ports:
      - "443:443"
    volumes:
      - ./config/mysql-client/conf.d:/etc/mysql/conf.d
      - ./config/mysql-client:/etc/mysql
      - ./logs/ubuntu_logs:/var/log/apache2
      - /etc/localtime:/etc/localtime
    privileged: true
    restart: always
    hostname: orangehrm-test-web_rhel
    container_name: test_web_rhel
